trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Debug'

steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Bajamos dependencias y compilamos la web app'

- task: DotNetCoreCLI@2
  displayName: 'Lanzamos los test'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Genero un zip con los ficheros de aplicacion web'
  inputs:
    command: publish
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'    
    publishWebProjects: true    
    zipAfterPublish: true
